
```{r include=FALSE}
library(dplyr)
library(raster)
#library(sp)
library(sf)

#install.packages("rWind")
library(rWind)

#load shapefile of farm sites
targets <- '/Users/Zack/0_seawarden/greece/blue_bridge/farm_500m_update_current.shp' 
#targets <- '/Users/Zack/0_seawarden/greece/colocation/greece_wind_500m_sq.shp'
targets <- st_read(targets)

#load ocean current data
vo <- '/Users/Zack/0_current/vo_tif/' 
uo <- '/Users/Zack/0_current/uo_tif/'

#output folder - for combine
output_csv <- '/Users/Zack/0_current/current_csv/'
```

```{r}
#function to crop raster to area of interest, converts raster to point
crop_tool <- function(image_file, target){
  
  #opens raster file, clips raster to target (target is opened in a prior step)
  raster_crop <- crop(raster(image_file), target) 
  
  #raster clip is convereted to a point
  pts <- rasterToPoints(raster_crop) 
  
  #points converted to a df
  pts_df <- as.data.frame(pts) 
  
  #mean calculated to result in just one measurement
  mean(pts_df[,3])} 
```

```{r}
current_tool <- function(v_folder, u_folder, target){ 

  #list of tif files in folder
  v_list <- list.files(v_folder, pattern = '.tif')
  u_list <- list.files(u_folder, pattern = '.tif')
  
  daily_u = list()
  daily_v = list()
  date = list()

  #for (i in 1:5){
  for (i in 1:length(v_list)){

      v_file <- paste0(v_folder, v_list[i])
      u_file <- paste0(u_folder, u_list[i])

      v <- crop_tool(v_file, target)
      u <- crop_tool(u_file, target)

      daily_u[[i]] <- u
      daily_v[[i]] <- v
      
        day <- substr(u_list[i], 19, 20)
        month <- substr(u_list[i], 16, 17)
        year <- substr(u_list[i], 11, 14)

      date[[i]] <- paste0(day, "/", month, "/", year)}
  
  daily_v[is.na(daily_v)] = 0
  daily_u[is.na(daily_u)] = 0
  
  daily_v = do.call(rbind, daily_v)
  daily_u = do.call(rbind, daily_u)
  date = data.frame(do.call(rbind, date))
  
  #daily_v <- as.data.frame(daily_v)
  #daily_u <- as.data.frame(daily_u)
  
  #colnames(date) <- c("date")
  #colnames(daily_v) <- c("v")
  #colnames(daily_u) <- c("u")
  
  #combine
  daily <- cbind(date, uv2ds(u=daily_u, v=daily_v))
  #daily <- cbind(date, daily_v, daily_u)
  
  #rename columns
  daily <- daily %>% rename(date=1, dir=2, speed=3)}

```

```{r include=FALSE}
for (i in 26:nrow(targets)){
#for (i in 1:5){
  target <- targets[i, ]
  df <- current_tool(vo, uo, target)
  #filename <- paste0(output_csv, target$farm_id, '_current.csv')
  filename <- paste0(output_csv, targets$Id[i], '_current.csv')
  write.table(df, file = filename, row.names=FALSE, col.names = TRUE, sep=",")}
```

```{r}
list <- list.files(output_csv, pattern = '.csv')

avg = list()
farm_id = list()

for (i in list){
  csv <- read.delim(paste0(output_csv, i), sep = ',', stringsAsFactors = F, header = TRUE)
  avg[[i]] <- mean(csv$speed)
  farm_id[[i]] <- unlist(strsplit(i, "_"))[1]}
    

avg_df <-data.frame(do.call(rbind, avg))
id_df <-data.frame(do.call(rbind, farm_id))
bath_df <-cbind(id_df, avg_df)
bath_df <- bath_df %>% rename(farm_site=1, avg_speed=2)

output <- '/Users/Zack/0_current/current_avg.csv'
write.table(bath_df, file = output, row.names=FALSE, col.names = FALSE, sep=",")

```

```{r}
# #combine 2018 and 2019 csv files
# combine <- function(output_18, output_19, output_csv){
# 
#   #read csv files
#   csv_1 <- read.delim(paste0(output_18, list_1[i]), sep = ',', stringsAsFactors = F, header = FALSE)
#   csv_2 <- read.delim(paste0(output_19, list_1[i]), sep = ',', stringsAsFactors = F, header = FALSE)
# 
#   #create output filename
#   output <- paste0(output_csv, paste0(list_1[i]))
# 
#   #merge dataframes and export file
#   write.table(rbind(csv_1, csv_2), file = paste0(output_csv, paste0(list_1[i])), row.names=FALSE, col.names = FALSE, sep=",")}
# 
# #list files in folders
# list_1 <- list.files(output_18, pattern = '.csv')
# list_2 <- list.files(output_19, pattern = '.csv')
# 
# #combine SST csv files
# for (i in 1:(length(list_1))){combine(output_18, output_19, output_csv)}
```
