---
title: "rac_seabass_all"
author: "Zack Dinh"
date: "September 4, 2019"
output: html_document
---

```{r include=FALSE}
library(RAC)
library(dplyr)
library(zoo) #index function
#command + shift + c
trace(Bass_pop_main,edit=T) #delete selector = "y"

#generate prep files for all sites
farmsites <- read.csv('/Users/Zack/0_seawarden/r_rac/master_inventory - Farm_Sites.csv', header=TRUE, sep=",")
sites <- as.vector(farmsites$farm_site)

#select sites to model
sites_2 <- list(23, 71, 92, 165, 172, 219) #study sites
#sites_2 <- list(23, 71, 92)
#sites_2 <- list(0, 1, 2)
#sites_2 <- list(23)

#specify number of simulations 1) feeding 2), full simulation
# pre_sim <- 50
# main_sim <- 5000

pre_sim <- 5
main_sim <- 500

# start <- "3/1/2018" #jan 3, 2018
# end_prep <- "4/9/2019"
# end <- "31/8/2019"

start <- "1/4/2018" #apr 1, 2018
end_prep <- "19/12/2019"
end <- "15/12/2019"
```

```{r include=FALSE}
#load sst files
sst_folder <- '/Users/Zack/0_thesis_sst/ghrsst_csv/'
sst_list <- list.files(sst_folder, pattern = '.csv')

#load master files
rac_folder <- "/Users/Zack/0_seawarden/r_rac/rac_seabass/"
master_files <- paste0(rac_folder, 'master_files/master_RAC-seabass - ')

#prep files to generate feeding tables
feeding_prep <- read.csv(paste0(master_files, 'Feeding_Prep.csv'), header=TRUE, sep=",")

#files for both steps
population <- read.csv(paste0(master_files, 'Population.csv'), header=FALSE, sep=",", stringsAsFactors = FALSE)
parameters <- read.csv(paste0(master_files, 'Parameters.csv'), header=FALSE, sep=",", stringsAsFactors = FALSE)
management <- read.csv(paste0(master_files, 'Management.csv'), header=FALSE, sep=",")
food <- read.csv(paste0(master_files, 'Food_Characterization.csv'), header=FALSE, sep=",")
```

```{r include=FALSE}
#create folder for each site, #add SST data
# for (i in sites){
# 
#   #create a folder for each site
#   site_folder <- paste0(rac_folder, 'site_', i, '/')
#   dir.create(site_folder)
# 
#   #create RAC folders for each site
#   Bass_pop_skeleton(site_folder)
# 
#   #add SST data
#   orglocation <- paste0(sst_folder, i, '_sst.csv')
#   newlocation <- paste0(site_folder, 'Bass_population/Inputs/Forcings/')
#   file.copy(from=orglocation, to=newlocation, overwrite = TRUE, recursive = FALSE, copy.mode = TRUE)
#   file.remove(paste0(newlocation, 'Water_temperature.csv'))
#   file.rename(paste0(newlocation, i, '_sst.csv'), paste0(newlocation, 'Water_temperature.csv'))}
```

```{r}
#load prep files for each site

#generate Population.csv for each site
for (i in index(sites)){
  column <- i + 4
  export <- population %>% select(1, 2, column, 3, 4)
    export[9, 3] = pre_sim
  site <- (population %>% select(column))[1,]
  output <- paste0(rac_folder, 'site_', site, '/Bass_population/Inputs/Parameters/Population.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Parameters.csv for each site 
for (i in sites){
  export <- parameters %>% select(1, 2, 5, 3, 4) #5 prep parameters
      export[23, 3] = start
      export[24, 3] = end_prep
  output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Parameters/Parameters.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Feeding.csv for each site
for (i in sites){
  output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Forcings/Feeding.csv')
  write.table(feeding_prep, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Management.csv for each site 
for (i in sites){
  export <- management %>% select(1, 2, 3)
  output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Population_management/Management.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Food_Characterization.csv for each site 
for (i in sites){
  export <- food %>% select(2, 1)
  export <- export[-1,] #drop header
  output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Forcings/Food_Characterization.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}
```

```{r include=FALSE}
#first model run to generate feeding tables
for (i in sites_2){
  userpath <- paste0(rac_folder, "site_", i)
  setwd(userpath) #working directory
  forcings <- Bass_pop_dataloader(userpath) #load environmental variables
  output <- Bass_pop_main(userpath, forcings)} #run growth model
```

```{r}
#generate final feeding tables
feeding <- function(rac_folder, i){

  site_folder <- paste0('site_', i, '/Bass_population/Outputs/Out_csv/')
  ingestion <- read.csv(paste0(rac_folder, site_folder, 'actual_ingestion.csv'), header=TRUE, sep=",")

  ingestion <- ingestion %>% select(V1)
  
  date <- feeding_prep %>% select(date)
  #date <- date$date[1:nrow(ingestion)]
  
  date <- date$date[92:718]
  compiled <- cbind(date, ingestion)

  name <- paste0(rac_folder, 'feeding_files/site_', i, '_feeding.csv')
  write.table(compiled, file = name, row.names=FALSE, col.names = TRUE, sep=",")}

for (i in sites_2){feeding(rac_folder, i)}
```

```{r}
#load data for final model run

#generate Population.csv for each site
for (i in index(sites)){
  column <- i + 4
  export <- population %>% select(1, 2, column, 3, 4)
    export[9, 3] = main_sim
  site <- (population %>% select(column))[1,]
  output <- paste0(rac_folder, 'site_', site, '/Bass_population/Inputs/Parameters/Population.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Parameters.csv for each site
for (i in sites_2){
  export <- parameters %>% select(1, 2, 6, 3, 4) #6 final parameters
    export[23, 3] = start
    export[24, 3] = end
  output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Parameters/Parameters.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Feeding.csv for each site
for (i in sites_2){
  feed <- read.csv(paste0(rac_folder, 'feeding_files/site_', i, '_feeding.csv'))
  output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Forcings/Feeding.csv')
  write.table(feed, file = output, row.names=FALSE, col.names = FALSE, sep=",")}
```

```{r include=FALSE}
for (i in sites_2){
  userpath <- paste0(rac_folder, "site_", i)
  setwd(userpath) #working directory
  forcings <- Bass_pop_dataloader(userpath) #load environmental variables
  output <- Bass_pop_main(userpath, forcings)} #run growth model
```
