---
title: "rac_bream_all"
author: "Zack Dinh"
date: "September 4, 2019"
output: html_document
---

```{r include=FALSE}
library(RAC)
library(dplyr)
#command + shift + c

#sites <- list(23, 71, 92, 165, 172, 219) #study sites
sites <- list(23, 71, 92) #study sites
sites <- 

#load sst files
sst_folder <- '/Users/Zack/0_thesis_sst/ghrsst_csv_test/'
sst_list <- list.files(sst_folder, pattern = '.csv')

#load master files
rac_folder <- "/Users/Zack/0_seawarden/r_rac/rac_bream/"
master_files <- paste0(rac_folder, 'master_files/master_RAC-bream - ')

#prep files to generate feeding tables
feeding_prep <- read.csv(paste0(master_files, 'Feeding_Prep.csv'), header=TRUE, sep=",")
population_prep <- read.csv(paste0(master_files, 'Population_Prep.csv'), header=FALSE, sep=",")

#files for final model run
population <- read.csv(paste0(master_files, 'Population.csv'), header=FALSE, sep=",")
parameters <- read.csv(paste0(master_files, 'Parameters.csv'), header=FALSE, sep=",")

#files for both steps
management <- read.csv(paste0(master_files, 'Management.csv'), header=FALSE, sep=",")
food <- read.csv(paste0(master_files, 'Food_Characterization.csv'), header=FALSE, sep=",")
```

```{r include=FALSE}
#create folder for each site, #add SST data
for (i in sites){
  
  #create a folder for each site
  site_folder <- paste0(rac_folder, 'site_', i, '/')
  dir.create(site_folder) 
  
  #create RAC folders for each site
  Bream_pop_skeleton(site_folder) 
  
  #add SST data
  orglocation <- paste0(sst_folder, i, '_sst.csv')
  newlocation <- paste0(site_folder, 'Bream_population/Inputs/Forcings/')
  file.copy(from=orglocation, to=newlocation, overwrite = TRUE, recursive = FALSE, copy.mode = TRUE)
  file.remove(paste0(newlocation, 'Water_temperature.csv'))
  file.rename(paste0(newlocation, i, '_sst.csv'), paste0(newlocation, 'Water_temperature.csv'))}
```

```{r}
#load prep files for each site

#generate Population.csv for each site
for (i in sites){
  for (j in 0:(length(sites)-1)){
    column <- j + 5 #!
    export <- population_prep %>% select(1, 2, column, 3, 4)}
    output <- paste0(rac_folder, 'site_', i, '/Bream_population/Inputs/Parameters/Population.csv')
    write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Parameters.csv for each site 
for (i in sites){
  export <- parameters %>% select(1, 2, 5, 3, 4) #5 prep parameters
  output <- paste0(rac_folder, 'site_', i, '/Bream_population/Inputs/Parameters/Parameters.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Feeding.csv for each site
for (i in sites){
  output <- paste0(rac_folder, 'site_', i, '/Bream_population/Inputs/Forcings/Feeding.csv')
  write.table(feeding_prep, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Management.csv for each site 
for (i in sites){
  export <- management %>% select(1, 2, 3)
  output <- paste0(rac_folder, 'site_', i, '/Bream_population/Inputs/Population_management/Management.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Food_Characterization.csv for each site 
for (i in sites){
  export <- food %>% select(2, 1)
  export <- export[-1,] #drop header
  output <- paste0(rac_folder, 'site_', i, '/Bream_population/Inputs/Forcings/Food_Characterization.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}
```

```{r}
#first model run to generate feeding tables (using lapply instead of a forloop)
trace(Bream_pop_main,edit=T) #delete selector = "y"

# pre_rac <- function(sites){
#   userpath <- paste0(rac_folder, "site_", i)
#   setwd(userpath) #working directory
#   forcings <- Bream_pop_dataloader(userpath) #load environmental variables
#   output <- Bream_pop_main(userpath, forcings)} #run growth model
# lapply(sites, pre_rac)

for (i in sites){
  userpath <- paste0(rac_folder, "site_", i)
  setwd(userpath) #working directory
  forcings <- Bream_pop_dataloader(userpath) #load environmental variables
  output <- Bream_pop_main(userpath, forcings)} #run growth model
```

# ```{r}
# #generate final feeding tables
# feeding <- function(rac_folder, i){
# 
#   site_folder <- paste0('site_', i, '/Bream_population/Outputs/Out_csv/')
#   ingestion <- read.csv(paste0(rac_folder, site_folder, 'actual_ingestion.csv'), header=TRUE, sep=",")
# 
#   ingestion <- ingestion %>% select(V1)
#   compiled <- cbind(date, ingestion)
# 
#   name <- paste0(rac_folder, 'feeding_files/site_', i, '_feeding.csv')
#   write.table(compiled, file = name, row.names=FALSE, col.names = TRUE, sep=",")}
# 
# date <- feeding_prep %>% select(date)
# date <- date$date[1:547]
# 
# for (i in sites){
#   feeding(rac_folder, i)}
# ```
# 
# ```{r}
# #load data for final model run
# 
# #generate Population.csv for each site
# for (i in sites){
#   for (j in 0:(length(sites)-1)){
#     column <- j + 5
#     export <- population %>% select(1, 2, column, 3, 4)}
#     output <- paste0(rac_folder, 'site_', i, '/Bream_population/Inputs/Parameters/Population.csv')
#     write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}
# 
# #generate Parameters.csv for each site
# for (i in sites){
#   export <- parameters %>% select(1, 2, 6, 3, 4) #6 final parameters
#   output <- paste0(rac_folder, 'site_', i, '/Bream_population/Inputs/Parameters/Parameters.csv')
#   write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}
# 
# #generate Feeding.csv for each site
# for (i in sites){
#   feed <- read.csv(paste0(rac_folder, 'feeding_files/site_', i, '_feeding.csv'))
#   output <- paste0(rac_folder, 'site_', i, '/Bream_population/Inputs/Forcings/Feeding.csv')
#   write.table(feed, file = output, row.names=FALSE, col.names = FALSE, sep=",")}
# ```
# 
# ```{r include=FALSE}
# for (i in sites){
#   userpath <- paste0(rac_folder, "site_", i)
#   setwd(userpath) #working directory
#   forcings <- Bream_pop_dataloader(userpath) #load environmental variables
#   output <- Bream_pop_main(userpath, forcings)} #run growth model
# ```
