---
title: "rac_seabass_all"
author: "Zack Dinh"
date: "September 4, 2019"
output: html_document
---

```{r include=FALSE}
library(RAC)
library(dplyr)
#command + shift + c

#load sst files
sst_folder <- '/Users/Zack/0_thesis_sst/ghrsst_csv_test/'
sst_list <- list.files(sst_folder, pattern = '.csv')

#load master files
rac_folder <- "/Users/Zack/0_seawarden/r_rac/rac_seabass/"
master_files <- paste0(rac_folder, 'master_files/')

#prep files to generate feeding tables
master_Feeding_Prep <- read.csv(paste0(master_files, 'master_RAC-seabass - Feeding_Prep.csv'), header=TRUE, sep=",")
master_Population_Prep <- read.csv(paste0(master_files, 'master_RAC-seabass - Population_Prep.csv'), header=FALSE, sep=",")

#files for final model run
master_Population <- read.csv(paste0(master_files, 'master_RAC-seabass - Population.csv'), header=FALSE, sep=",")
master_Parameters <- read.csv(paste0(master_files, 'master_RAC-seabass - Parameters.csv'), header=FALSE, sep=",")

#files for both steps
master_Management <- read.csv(paste0(master_files, 'master_RAC-seabass - Management.csv'), header=FALSE, sep=",")
master_Food <- read.csv(paste0(master_files, 'master_RAC-seabass - Food_Characterization.csv'), header=FALSE, sep=",")
```

```{r include=FALSE}
#create folder for each site, #add SST data

#sites <- length(sst_list)
#sites <- 5
sites <- list(23, 71, 92, 165, 172, 219) #study sites
#sites <- list(23)
 
for (i in sites){
  #create a folder for each site
  site_folder <- paste0(rac_folder, 'site_', i, '/')  
  dir.create(site_folder) 
  
  #create RAC folders for each site
  Bass_pop_skeleton(site_folder) 
  
  #add SST data
  orglocation <- paste0(sst_folder, i, '_sst.csv')
  newlocation <- paste0(site_folder, 'Bass_population/Inputs/Forcings/')
  file.copy(from=orglocation, to=newlocation, overwrite = TRUE, recursive = FALSE, copy.mode = TRUE)
  file.remove(paste0(newlocation, 'Water_temperature.csv'))
  file.rename(paste0(newlocation, i, '_sst.csv'), paste0(newlocation, 'Water_temperature.csv'))}
```

```{r}
#load prep files for each site

#generate Population.csv for each site
for (i in sites){
  for (j in 0:(length(sites)-1)){
    column <- j + 5
    export <- master_Population_Prep %>% select(1, 2, column, 3, 4)}
    output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Parameters/Population.csv')
    write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Parameters.csv for each site 
for (i in sites){
  export <- master_Parameters %>% select(1, 2, 5, 3, 4) #5 prep parameters
  output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Parameters/Parameters.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Feeding.csv for each site
for (i in sites){
  export <- master_Feeding_Prep %>% select(1, 2)
  output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Forcings/Feeding.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Management.csv for each site 
for (i in sites){
  export <- master_Management %>% select(1, 2, 3)
  output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Population_management/Management.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Food_Characterization.csv for each site 
for (i in sites){
  export <- master_Food %>% select(2, 1)
  export <- export[-1,] #drop header
  output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Forcings/Food_Characterization.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}
```

```{r include=FALSE}
#first model run to generate feeding tables

#delete selector = "y"
trace(Bass_pop_main,edit=T)

for (i in sites){
  userpath <- paste0(rac_folder, "site_", i)
  
  #working directory
  setwd(userpath) 
  
  #load environmental variables
  forcings <- Bass_pop_dataloader(userpath) 
 
  #run growth model
  output <- Bass_pop_main(userpath, forcings)}
```

```{r}
#generate final feeding tables
feeding <- function(rac_folder, i){
  
  site_folder <- paste0('site_', i, '/Bass_population/Outputs/Out_csv/') 
  ingestion <- read.csv(paste0(rac_folder, site_folder, 'actual_ingestion.csv'), header=TRUE, sep=",")
  
  ingestion <- ingestion %>% select(V1)
  compiled <- cbind(date, ingestion)
  
  name <- paste0(rac_folder, 'feeding_files/site_', i, '_feeding.csv')
  write.table(compiled, file = name, row.names=FALSE, col.names = TRUE, sep=",")}

date <- master_Feeding_Prep %>% select(date)
date <- date$date[1:547]

for (i in sites){
  feeding(rac_folder, i)}
```

```{r}
#load data for final model run

#generate Population.csv for each site
for (i in sites){
  for (j in 0:(length(sites)-1)){
    column <- j + 5
    export <- master_Population %>% select(1, 2, column, 3, 4)}
    output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Parameters/Population.csv')
    write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Parameters.csv for each site 
for (i in sites){
  export <- master_Parameters %>% select(1, 2, 6, 3, 4) #final parameters
  output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Parameters/Parameters.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Feeding.csv for each site
for (i in sites){
  feed <- read.csv(paste0(rac_folder, 'feeding_files/site_', i, '_feeding.csv'))
  export <- feed %>% select(1, 2)
  output <- paste0(rac_folder, 'site_', i, '/Bass_population/Inputs/Forcings/Feeding.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}
```

```{r include=FALSE}
for (i in sites){
  userpath <- paste0(rac_folder, "site_", i)
  
  #working directory
  setwd(userpath) 
  
  #load environmental variables
  forcings <- Bass_pop_dataloader(userpath) 
 
  #run growth model
  output <- Bass_pop_main(userpath, forcings)}
```
