```{r setup, include=FALSE}
library(dplyr)

#create one csv per farm site
farmsites <- read.csv('./master_inventory - Farm_Sites.csv', header=TRUE, sep=",")
sites <- as.vector(farmsites$farm_site)
#sites <- sites[1]

bream_folder <- "./rac_bream/"
site_folder_bream <- '/Bream_population/Outputs/Out_csv/'

bass_folder <- "./rac_seabass/"
site_folder_bass <- '/Bass_population/Outputs/Out_csv/'
```

```{r}
#function to combine RAC predictions from one farm site in to one csv file
compiler <- function(rac_folder, site_folder, i, ingest_rate){

  filepath <- paste0(rac_folder, 'site_', i, site_folder)
  
  #load csv files
  pop <- read.csv(paste0(filepath, 'population.csv'), header=TRUE, sep=",")  
  faeces_c <- read.csv(paste0(filepath, 'faeces_production_Carbohydrates.csv'), header=TRUE, sep=",")
  faeces_l <- read.csv(paste0(filepath, 'faeces_production_Lipids.csv'), header=TRUE, sep=",")
  faeces_p <- read.csv(paste0(filepath, 'faeces_production_Proteins.csv'), header=TRUE, sep=",")

  ingest <- read.csv(paste0(filepath, 'actual_ingestion.csv'), header=TRUE, sep=",")
  weight <- read.csv(paste0(filepath, 'weight.csv'), header=TRUE, sep=",")  
  
  #extract columns
  pop <- pop %>% select(x) 
  faeces_c <- faeces_c %>% select(X, V1)
  faeces_l <- faeces_l %>% select(V1)
  faeces_p <- faeces_p %>% select(V1)

  feed_c <- ingest %>% select(V1) * ingest_rate * .19 * pop[1,] / 1000
  feed_l <- ingest %>% select(V1) * ingest_rate * .21 * pop[1,] / 1000
  feed_p <- ingest %>% select(V1) * ingest_rate * .44 * pop[1,] / 1000
  weight <- weight %>% select(V1) %>% slice(1:nrow(faeces_c))
  
  #compile columns to new dataframe
  compiled <- cbind(faeces_c, faeces_l, faeces_p, feed_c, feed_l, feed_p, weight)
  
  #rename columns
  colnames(compiled) <- c("day", "faeces_c", "faeces_l", "faeces_p", "feed_c", "feed_l", "feed_p", "weight")
  
  #write csv
  name <- paste0(rac_folder, 'output_compiled/site_', i, '_compiled.csv')
  write.table(compiled, file = name, row.names=FALSE, col.names = TRUE, sep=",")}
```

```{r}
for (i in sites){
  compiler(bream_folder, site_folder_bream, i, 1.3) #.7
  compiler(bass_folder, site_folder_bass, i, 1.05)} #.95
```

```{r}
#function to combine farm site csv files to single csv
compiler_all <- function(rac_folder, site_folder, i){
  #load csv files
  id <- unlist(strsplit(i, "_"))[2]
  harvest <-  read.csv(paste0(rac_folder, 'site_', id, site_folder, 'Days_to_commercial_size.csv'))
  compiled <- read.csv(paste0(rac_folder, 'output_compiled/', i), header=TRUE, sep=",") 
  
  #extract columns
  harvest <- harvest %>% select(2)
  harvest <- harvest[[1]]
  
  #sum rows by days of harvest
  compiled <- compiled[1:harvest,] %>% select(2, 3, 4, 5, 6, 7)
  compiled <- round(colSums(compiled))
  compiled <- as.vector(c(id, compiled, harvest))}
```

```{r}
#combine all
names <- c("site_ID", "faeces_c", "faeces_l", "faeces_p", "feed_c", "feed_l", "feed_p", "harvest day") #colnames

#bream
sites <- list.files(paste0(bream_folder, 'output_compiled/'), pattern = '.csv')

  combined = list()
  for (i in sites){combined[[i]] <- compiler_all(bream_folder, site_folder_bream, i)}
  
  combined_df<-data.frame(do.call(rbind, combined))
    colnames(combined_df) <- names
  
  #export dataframe as csv
  write.table(combined_df, file = paste0('./combined_bream.csv'), row.names=FALSE, col.names = TRUE, sep=",")

#bass
sites <- list.files(paste0(bass_folder, 'output_compiled/'), pattern = '.csv')

  combined = list()
  for (i in sites){combined[[i]] <- compiler_all(bass_folder, site_folder_bass, i)}
  
  combined_df<-data.frame(do.call(rbind, combined))
    colnames(combined_df) <- names
  
  #export dataframe as csv
  write.table(combined_df, file = paste0('./combined_seabass.csv'), row.names=FALSE, col.names = TRUE, sep=",")
```