```{r setup, include=FALSE}
library(dplyr)

#create one csv per farm site
farmsites <- read.csv('/Users/Zack/0_seawarden/r_rac/master_inventory - Farm_Sites.csv', header=TRUE, sep=",")
sites <- as.vector(farmsites$farm_site)
sites <- sites[1:5]

#rac_folder <- '/Users/Zack/0_rac/rac_bream/'
rac_folder <- "/Users/Zack/0_seawarden/r_rac/rac_bream/"
site_folder <- '/Bream_population/Outputs/Out_csv/'

#rac_folder_2 <- '/Users/Zack/0_rac/rac_seabass/'
rac_folder_2 <- "/Users/Zack/0_seawarden/r_rac/rac_seabass/"
site_folder_2 <- '/Bass_population/Outputs/Out_csv/'
```

```{r}
#function to combine RAC predictions from one farm site in to one csv file
compiler <- function(rac_folder, site_folder, i){

  filepath <- paste0(rac_folder, 'site_', i, site_folder)
  
  #load csv files
  faeces_c <- read.csv(paste0(filepath, 'faeces_production_Carbohydrates.csv'), header=TRUE, sep=",")
  faeces_l <- read.csv(paste0(filepath, 'faeces_production_Lipids.csv'), header=TRUE, sep=",")
  faeces_p <- read.csv(paste0(filepath, 'faeces_production_Proteins.csv'), header=TRUE, sep=",")
  
  feed_c <- read.csv(paste0(filepath, 'wasted_feed_Carbohydrates.csv'), header=TRUE, sep=",")
  feed_l <- read.csv(paste0(filepath, 'wasted_feed_Lipids.csv'), header=TRUE, sep=",")
  feed_p <- read.csv(paste0(filepath, 'wasted_feed_Proteins.csv'), header=TRUE, sep=",")

  nh4 <- read.csv(paste0(filepath, 'NH4_release.csv'), header=TRUE, sep=",")  
  weight <- read.csv(paste0(filepath, 'weight.csv'), header=TRUE, sep=",")  

  #extract columns
  faeces_c <- faeces_c %>% select(X, V1, V2)
  faeces_l <- faeces_l %>% select(V1, V2)
  faeces_p <- faeces_p %>% select(V1, V2)
  
  feed_c <- feed_c %>% select(V1, V2)
  feed_l <- feed_l %>% select(V1, V2)
  feed_p <- feed_p %>% select(V1, V2)
  
  nh4 <- nh4 %>% select(V1, V2)
  weight <- weight %>% select(V1, V2) %>% slice(1:nrow(faeces_c))

  #compile columns to new dataframe
  compiled <- cbind(faeces_c, faeces_l, faeces_p, feed_c, feed_l, feed_p, nh4, weight)
  
  #rename columns
  colnames(compiled) <- c("day", "faeces_c1", "faeces_c2", "faeces_l1", "faeces_l2", "faeces_p1", "faeces_p2", 
                          "feed_c1", "feed_c2", "feed_l1", "feed_l2", "feed_p1", "feed_p2", 
                          "nh4_1", "nh4_2", "weight_1", "weight_2")
  
  #write csv
  name <- paste0(rac_folder, 'output_compiled/site_', i, '_compiled.csv')
  write.table(compiled, file = name, row.names=FALSE, col.names = TRUE, sep=",")}
```

```{r}
for (i in sites){
  compiler(rac_folder, site_folder, i)
  compiler(rac_folder_2, site_folder_2, i)} #sebass
```

```{r}
#function to combine farm site csv files to single csv
compiler_all <- function(rac_folder, site_folder, i){
  #load csv files
  id <- unlist(strsplit(i, "_"))[2]
  harvest <-  read.csv(paste0(rac_folder, 'site_', id, site_folder, 'Days_to_commercial_size.csv'))
  compiled <- read.csv(paste0(rac_folder, 'output_compiled/', i), header=TRUE, sep=",") 
  
  #extract columns
  harvest <- harvest %>% select(2)
  harvest <- harvest[[1]]
  
  #sum rows by days of harvest
  compiled <- compiled[1:harvest,] %>% select(2, 4, 6, 8, 10, 12)
  compiled <- round(colSums(compiled))
  compiled <- as.vector(c(id, compiled, harvest))}
```

```{r}
#combine all
names <- c("site_ID", "faeces_c", "faeces_l", "faeces_p", "feed_c", "feed_l", "feed_p", "harvest day") #colnames

#bream
sites <- list.files(paste0(rac_folder, 'output_compiled/'), pattern = '.csv')

combined = list()
for (i in sites){combined[[i]] <- compiler_all(rac_folder, site_folder, i)}

combined_df<-data.frame(do.call(rbind, combined))
  colnames(combined_df) <- names

#export dataframe as csv
write.table(combined_df, file = paste0('./combined_bream.csv'), row.names=FALSE, col.names = TRUE, sep=",")

#bass
sites <- list.files(paste0(rac_folder_2, 'output_compiled/'), pattern = '.csv')

combined = list()
for (i in sites){combined[[i]] <- compiler_all(rac_folder_2, site_folder_2, i)}

combined_df<-data.frame(do.call(rbind, combined))
  colnames(combined_df) <- names

#export dataframe as csv
write.table(combined_df, file = paste0('./combined_seabass.csv'), row.names=FALSE, col.names = TRUE, sep=",")
```