---
title: "RAC compiler"
author: "Zack Dinh"
date: "December 24, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)

#compiler combines daily RAC predictions for each farmsite in to one csv file
compiler <- function(rac_folder, site_folder, i){

  #site_folder <- paste0('site_', i, '/Bass_population/Outputs/Out_csv/') 
  site_folder <- paste0('site_', i, '/Bream_population/Outputs/Out_csv/')
  
  #load csv files
  faeces_c <- read.csv(paste0(rac_folder, site_folder, 'faeces_production_Carbohydrates.csv'), header=TRUE, sep=",")
  faeces_l <- read.csv(paste0(rac_folder, site_folder, 'faeces_production_Lipids.csv'), header=TRUE, sep=",")
  faeces_p <- read.csv(paste0(rac_folder, site_folder, 'faeces_production_Proteins.csv'), header=TRUE, sep=",")
  
  feed_c <- read.csv(paste0(rac_folder, site_folder, 'wasted_feed_Carbohydrates.csv'), header=TRUE, sep=",")
  feed_l <- read.csv(paste0(rac_folder, site_folder, 'wasted_feed_Lipids.csv'), header=TRUE, sep=",")
  feed_p <- read.csv(paste0(rac_folder, site_folder, 'wasted_feed_Proteins.csv'), header=TRUE, sep=",")

  nh4 <- read.csv(paste0(rac_folder, site_folder, 'NH4_release.csv'), header=TRUE, sep=",")  
  weight <- read.csv(paste0(rac_folder, site_folder, 'weight.csv'), header=TRUE, sep=",")  

  #extract columns
  faeces_c <- faeces_c %>% select(X, V1, V2)
  faeces_l <- faeces_l %>% select(V1, V2)
  faeces_p <- faeces_p %>% select(V1, V2)
  
  feed_c <- feed_c %>% select(V1, V2)
  feed_l <- feed_l %>% select(V1, V2)
  feed_p <- feed_p %>% select(V1, V2)
  
  nh4 <- nh4 %>% select(V1, V2)
  weight <- weight %>% select(V1, V2) 
  weight1 <- weight$V1[1:543]
  weight2 <- weight$V2[1:543]

  #compile columns to new dataframe
  compiled <- cbind(faeces_c, faeces_l, faeces_p, feed_c, feed_l, feed_p, nh4, weight1, weight2)
  
  #rename columns
  colnames(compiled) <- c("day", 
                               "faeces_c1", "faeces_c2", "faeces_l1", "faeces_l2", "faeces_p1", "faeces_p2", 
                               "feed_c1", "feed_c2", "feed_l1", "feed_l2", "feed_p1", "feed_p2", 
                               "nh4_1", "nh4_2", "weight_1", "weight_2")
  
  #write csv
  name <- paste0(rac_folder, 'output_files/site_', i, '_compiled.csv')
  
  write.table(compiled, file = name, row.names=FALSE, col.names = TRUE, sep=",")}
```

```{r}
sites <- list(23, 71, 92, 165, 172, 219)

rac_seabass <- '/Users/Zack/0_seawarden/r_rac/rac_seabass/'

for (i in sites){
  compiler(rac_seabass, site_folder, i)}

rac_bream <- '/Users/Zack/0_seawarden/r_rac/rac_bream/'

for (i in sites){
  compiler(rac_bream, site_folder, i)}
```

```{r}
for (i in sim_list){
  sim_list <- list.files(rac_folder, pattern = 'sim')
  
  site_folder <- '/site_0/Bass_population/Outputs/Out_csv/'
  
  #load csv files
  faeces_c <- read.csv(paste0(rac_folder, i, site_folder, 'faeces_production_Carbohydrates.csv'), header=TRUE, sep=",")
  faeces_l <- read.csv(paste0(rac_folder, i, site_folder, 'faeces_production_Lipids.csv'), header=TRUE, sep=",")
  faeces_p <- read.csv(paste0(rac_folder, i, site_folder, 'faeces_production_Proteins.csv'), header=TRUE, sep=",")

  #extract columns
  faeces_c <- faeces_c %>% select(X, V1, V2)
  faeces_l <- faeces_l %>% select(V1, V2)
  faeces_p <- faeces_p %>% select(V1, V2)
  
  #compile columns to new dataframe
  compiled <- cbind(faeces_c, faeces_l, faeces_p)

  #rename columns
  colnames(compiled) <- c("day", "faeces_c_1", "faeces_c_2", "faeces_l_1", "faeces_l_2", "faeces_p_1", "faeces_p_2")
  
  name = paste0(rac_folder, 'RAC_seabass_compiled/', i, '_compiled.csv')
  write.table(compiled, file = name, row.names=FALSE, col.names = TRUE, sep=",")}
```