---
title: "Untitled"
author: "Zack Dinh"
date: "7/3/2020"
output: html_document
---

```{r setup, include=FALSE}
library(leaflet)
library(leaflet.extras)
library(geojsonio)
library(leafpop)
```

```{r}
src_aoi = "https://raw.githubusercontent.com/zdinh/seawarden/master/0_search_areas/3_aoi/"
src = "https://raw.githubusercontent.com/zdinh/seawarden/master/targets_2_simrdwn/"
grc_img = "GRC/test_ssd_imagery_controlset_2020_04_15_06-47-03/"

aoi = "_aoi.geojson"
frm = "_simrdwn_farmsites_ext.geojson"
pen = "_simrdwn_pens.geojson"
pts = "_simrdwn_farm_pts.geojson"

f = "GRC"
grc_aoi <- geojson_read(paste0(src_aoi, f, aoi),  what = "sp")
grc_frm <- geojson_read(paste0(src, f, "/", f, frm), what = "sp")
grc_pen <- geojson_read(paste0(src, f, "/", f, pen), what = "sp")
grc_pts <- geojson_read(paste0(src, f, "/", f, pts), what = "sp")
```

```{r}
base = "https://mts1.google.com/vt/lyrs=s&hl=en&src=app&x={x}&y={y}&z={z}&s=G"
att = "Sea Warden | Google"

img = paste0(src, grc_img, "133_18_38_4666_26_1479_38_4576_26_1594_thresh%3D0.25..jpeg")
url = paste0("Detections | ", "<a href=", img, ' target="_blank"', ">View Image</a>")
url
```


```{r}
map <-leaflet() %>%
  addTiles(urlTemplate = base, attribution = att) %>%
  setView(14, 40, zoom = 4) %>%
  setMaxBounds(-10, 50, 40, 30) %>%
  addFullscreenControl() %>%
  
  #data layers
  addPolygons(data=grc_aoi, color = 'white', weight = 1, fillOpacity = 0, popup = popupTable(grc_aoi, feature.id = FALSE, row.numbers = FALSE)) %>%
  addPolygons(data=grc_frm, color = '#3bb2d0', weight = 1, fillOpacity = 0, popup = popupTable(grc_frm, feature.id = FALSE, row.numbers = FALSE)) %>%
  addPolygons(data=grc_pen, color = '#3bb2d0', weight = 1, fillOpacity = 0, popup = popupTable(grc_pen, feature.id = FALSE, row.numbers = FALSE)) %>%
  addCircleMarkers(data=grc_pts, radius = .25, color = '#3bb2d0', popup = paste0(url, popupImage(img, src = "remote", height=300, width=300)))

map
```