---
title: "data prep MEDSEA"
author: "Zack Dinh"
date: "August 30, 2019"
output: html_document
---

```{r include=FALSE}
library(dplyr)
library(raster)
library(sf)

#load ocean current data
v_19 <- '/Users/Zack/0_thesis_ocean_current_2/vo_2019_tif/' #or 2019
u_19 <- '/Users/Zack/0_thesis_ocean_current_2/uo_2019_tif/' #or 2019

#output folder - for txt files
output_txt <- '/Users/Zack/0_thesis_ocean_current_2/current_txt/'
```

```{r}
#function to crop raster to area of interest, converts raster to point
crop_tool <- function(image_file, target){
  
  #opens raster file, clips raster to target (target is opened in a prior step)
  raster_crop <- crop(raster(image_file), target) 
  
  #raster clip is convereted to a point
  pts <- rasterToPoints(raster_crop) 
  
  #points converted to a df
  pts_df <- as.data.frame(pts) 
  
  #mean calculated to result in just one measurement
  mean(pts_df[,3])} 
```

```{r}
current_tool <- function(v_folder, u_folder, target, output){ 

  #list of tif files in folder
  v_list <- list.files(v_folder, pattern = '.tif')
  u_list <- list.files(u_folder, pattern = '.tif')
  
  daily_u = list()
  daily_v = list()
  date = list()

  #for (i in 1:5){
  for (i in 1:length(v_list)){

      v_file <- paste0(v_folder, v_list[i])
      u_file <- paste0(u_folder, u_list[i])

      v <- crop_tool(v_file, target)
      u <- crop_tool(u_file, target)

      daily_u[[i]] <- u
      daily_v[[i]] <- v

      day <- substr(u_list[i], 19, 20)
      month <- substr(u_list[i], 16, 17)
      year <- substr(u_list[i], 11, 14)

      date[[i]] <- paste0(day, "/", month, "/", year)}

  mean_u <-  mean(unlist(daily_u))
  mean_v <- mean(unlist(daily_v))
  
  mean_u <- rep(mean_u, 24)
  mean_v <- rep(mean_v, 24)
  
  daily <- cbind(mean_u, mean_v)
  
  #create output filename and export as csv
  df <-as.data.frame(target)
  filename <- paste0(output, paste0(df['farm_id']), '_current.txt')
  
  #create output file
  write.table(daily, file=filename, sep = "\t", row.names=FALSE, col.names=FALSE)}
```

```{r}
#load shapefile of farm sites
targets <- '/Users/Zack/0_seawarden/greece/blue_bridge/farm_pts_500m_sq_current.shp'
targets <- st_read(targets)

sites <- 1:nrow(as.data.frame(targets))
#sites <- sites[1:10]

#loop to create u, v, direction and speed csv for all farm sites
for (i in sites){current_tool(v_19, u_19, targets[i,], output_txt)}
```




