---
title: "rac_seabass_all"
author: "Zack Dinh"
date: "September 4, 2019"
output: html_document
---

```{r, echo=FALSE}
library(RAC)
library(dplyr)
setwd("../R/RAC_seabass_all/") #working directory
userpath <- "../R/RAC_seabass_all/" #userpath
```

```{r}
Bass_pop_main_revised <- function (userpath, forcings) 
{
    rm(list = ls())
    cat("Sea Bass population bioenergetic model\n")
    cat(" \n")
    currentpath = getwd()
    out_pre <- Bass_pop_pre(userpath, forcings)
    selector = "y"
    while (identical(selector, "y") == "TRUE") {
        cat(" \n")
        selector = readline("Do you want to change the inputs? [y/n]")
        if (identical(selector, "n") == "TRUE") {
            break
        }
        cat(" \n")
        cat("Insert forcings and parameters in the following folder\n")
        cat(paste0(userpath, "/Bass_population/Inputs\n"))
        cat(" \n")
        cat("Type y if you entered the correct inputs\n")
        cat("The data will be preprocessed again")
        selector = readline(" ")
        out_pre <- Bass_pop_pre(userpath, forcings)
        selector = "y"
    }
    Param = out_pre[[1]]
    Tint = out_pre[[2]]
    Gint = out_pre[[3]]
    Food = out_pre[[4]]
    IC = out_pre[[5]]
    times = out_pre[[6]]
    Dates = out_pre[[7]]
    N = out_pre[[8]]
    CS = out_pre[[9]]
    out_RKsolver <- Bass_pop_loop(Param, Tint, Gint, Food, IC, 
        times, N, userpath)
    out_post <- Bass_pop_post(userpath, out_RKsolver, times, 
        Dates, N, CS)
    cat(" ")
    cat("End")
    return(out_post)
}
```

```{r}
#command + shift + c
#load sst files
sst_folder <- '/Users/Zack/0_thesis_sst/ghrsst_2018_csv'
sst_list <- list.files(sst_folder, pattern = '.csv')

folder <- paste0(userpath, 'master_files_3/')

# load master files
# master_Feeding <- read.csv(paste0(folder, 'master_RAC - Feeding.csv'), header=TRUE, sep=",")
# master_Parameters <- read.csv(paste0(folder, 'master_RAC - Parameters.csv'), header=FALSE, sep=",")
# master_Management <- read.csv(paste0(folder, 'master_RAC - Management.csv'), header=FALSE, sep=",")
# master_Population <- read.csv(paste0(folder, 'master_RAC - Population.csv'), header=FALSE, sep=",")
# master_Food <- read.csv(paste0(folder, 'master_RAC - Food_Characterization.csv'), header=FALSE, sep=",")
master_Feeding <- read.csv(paste0(folder, 'master_RAC-seabass - Feeding.csv'), header=TRUE, sep=",")
master_Parameters <- read.csv(paste0(folder, 'master_RAC-seabass - Parameters.csv'), header=FALSE, sep=",")
master_Management <- read.csv(paste0(folder, 'master_RAC-seabass - Management.csv'), header=FALSE, sep=",")
master_Population <- read.csv(paste0(folder, 'master_RAC-seabass - Population.csv'), header=FALSE, sep=",")
master_Food <- read.csv(paste0(folder, 'master_RAC-seabass - Food_Characterization.csv'), header=FALSE, sep=",")
```

```{r}
#create folder for each site, #add SST data

#sites <- length(sst_list)
sites <- 0

for (i in 1:sites){
  #create a folder for each site
  path <- paste0(userpath, '/site_', i)  
  dir.create(path) 
  
  #create RAC folders for each site
  Bass_pop_skeleton(path) 
  
  #add SST data
  currentfiles <- paste0(sst_folder, '/', i, '_sst.csv')
  newlocation <- paste0(path, '/Bass_population/Inputs/Forcings/')
  file.copy(from=currentfiles, to=newlocation, overwrite = TRUE, recursive = FALSE, copy.mode = TRUE)
  file.remove(paste0(newlocation, 'Water_temperature.csv'))
  file.rename(paste0(newlocation, i, '_sst.csv'), paste0(newlocation, 'Water_temperature.csv'))}
```

```{r}
#generate Feeding.csv for each site
for (i in 1:sites){
  column <- i + 2
  export <- master_Feeding %>% select(1, column)
  output <- paste0(userpath, 'site_', i, '/Bass_population/Inputs/Forcings/Feeding.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Food_Characterization.csv for each site
for (i in 1:sites){
  column <- i + 2
  export <- master_Food %>% select(column, 1)
  export <- export[-1,] #drop header
  output <- paste0(userpath, 'site_', i, '/Bass_population/Inputs/Forcings/Food_Characterization.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Management.csv for each site
for (i in 1:sites){
  column1 <- 2
  column2 <- i + 3
  export <- master_Management %>% select(1, column1, column2)
  output <- paste0(userpath, 'site_', i, '/Bass_population/Inputs/Population_management/Management.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Parameters.csv for each site
for (i in 1:sites){
  column <- i + 5
  export <- master_Parameters %>% select(1, 2, column, 3, 4)
  output <- paste0(userpath, 'site_', i, '/Bass_population/Inputs/Parameters/Parameters.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}

#generate Population.csv for each site
for (i in 1:sites){
  column <- i + 5
  export <- master_Population %>% select(1, 2, column, 3, 4)
  output <- paste0(userpath, 'site_', i, '/Bass_population/Inputs/Parameters/Population.csv')
  write.table(export, file = output, row.names=FALSE, col.names = FALSE, sep=",")}
```

```{r}
#load and run model
for (i in 1:sites){
  userpath <- paste0(userpath, "/site_", i)
  
  #load environmental variables
  forcings <- Bass_pop_dataloader(userpath) 
 
  #run growth model
  #output <- Bass_pop_main_revised("../R", forcings)} 
  output <- Bass_pop_main("../R", forcings)} 
#trace(Bass_pop_main,edit=T)
```
