---
title: "RAC compiler"
author: "Zack Dinh"
date: "December 24, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)

#compiler combines daily RAC predictions for each farmsite in to one csv file
output_compiler <- function(rac_folder, i){
  
  #site folder
  site_folder <- paste0('site_', i, '/Bass_population/Outputs/Out_csv/') 
  
  #load csv files
  faeces_c <- read.csv(paste0(rac_folder, site_folder, 'faeces_production_Carbohydrates.csv'), header=TRUE, sep=",")
  faeces_l <- read.csv(paste0(rac_folder, site_folder, 'faeces_production_Lipids.csv'), header=TRUE, sep=",")
  faeces_p <- read.csv(paste0(rac_folder, site_folder, 'faeces_production_Proteins.csv'), header=TRUE, sep=",")
  
  feed_c <- read.csv(paste0(rac_folder, site_folder, 'wasted_feed_Carbohydrates.csv'), header=TRUE, sep=",")
  feed_l <- read.csv(paste0(rac_folder, site_folder, 'wasted_feed_Lipids.csv'), header=TRUE, sep=",")
  feed_p <- read.csv(paste0(rac_folder, site_folder, 'wasted_feed_Proteins.csv'), header=TRUE, sep=",")
  
  #extract columns
  faeces_c <- faeces_c %>% select(X, V1, V2)
  faeces_l <- faeces_l %>% select(V1, V2)
  faeces_p <- faeces_p %>% select(V1, V2)
  
  feed_c <- feed_c %>% select(V1, V2)
  feed_l <- feed_l %>% select(V1, V2)
  feed_p <- feed_p %>% select(V1, V2)
  
  #compile columns to new dataframe
  compiled <- cbind(faeces_c, faeces_l, faeces_p, feed_c, feed_l, feed_p)
  
  #rename columns
  colnames(compiled) <- c("day", 
                               "faeces_c1", "faeces_c2", "faeces_l1", "faeces_l2", "faeces_p1", "faeces_p2", 
                               "feed_c1", "feed_c2", "feed_l1", "feed_l2", "feed_p1", "feed_p2")
  
  #write csv
  name <- paste0(rac_folder, 'output_all_sites/site_', i, '_compiled.csv')
  
  write.table(compiled, file = name, row.names=FALSE, col.names = TRUE, sep=",")}
```

```{r}
rac_folder <- '/Users/Zack/0_seawarden/r/RAC_seabass_all/'
#output_compiler(rac_folder, 0)

sites <- 2
for (i in 0:sites){
  output_compiler(rac_folder, i)}
```